// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3XTvzncpn-tlWfdc2wQgsEet5xZLauXI',
    appId: '1:842578558977:web:abe5d1c05da3288d158000',
    messagingSenderId: '842578558977',
    projectId: 'coffee-spot-9a740',
    authDomain: 'coffee-spot-9a740.firebaseapp.com',
    databaseURL: 'https://coffee-spot-9a740-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coffee-spot-9a740.appspot.com',
    measurementId: 'G-KCTBC7F62P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQLu_3kVdmVEn-7cvyZK3VkdSaTlWNg1I',
    appId: '1:842578558977:android:3a25a0a5d6a3abcf158000',
    messagingSenderId: '842578558977',
    projectId: 'coffee-spot-9a740',
    databaseURL: 'https://coffee-spot-9a740-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coffee-spot-9a740.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwZ8zBGQU4chR84LIbrdq0X5mKHQNZU-4',
    appId: '1:842578558977:ios:f9f21331ac447770158000',
    messagingSenderId: '842578558977',
    projectId: 'coffee-spot-9a740',
    databaseURL: 'https://coffee-spot-9a740-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coffee-spot-9a740.appspot.com',
    iosBundleId: 'com.example.coffeeSpot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwZ8zBGQU4chR84LIbrdq0X5mKHQNZU-4',
    appId: '1:842578558977:ios:f9f21331ac447770158000',
    messagingSenderId: '842578558977',
    projectId: 'coffee-spot-9a740',
    databaseURL: 'https://coffee-spot-9a740-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coffee-spot-9a740.appspot.com',
    iosBundleId: 'com.example.coffeeSpot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3XTvzncpn-tlWfdc2wQgsEet5xZLauXI',
    appId: '1:842578558977:web:6da138be6fc120ea158000',
    messagingSenderId: '842578558977',
    projectId: 'coffee-spot-9a740',
    authDomain: 'coffee-spot-9a740.firebaseapp.com',
    databaseURL: 'https://coffee-spot-9a740-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coffee-spot-9a740.appspot.com',
    measurementId: 'G-T093S93ER9',
  );

}